import type { CanonicalIngredient } from '@/lib/db/types';

// 200-ingredient starter list. IDs are stable; names are display-only.
// aisle_group values: produce | dairy | meat | seafood | pantry | frozen | bakery | deli | beverage | snack
export const CANONICAL_INGREDIENTS: CanonicalIngredient[] = [
  // Produce - vegetables
  { id: 'yellow_onion', name: 'Yellow Onion', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'red_onion', name: 'Red Onion', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'garlic', name: 'Garlic', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'ginger', name: 'Ginger', category: 'vegetable', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'carrot', name: 'Carrots', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'celery', name: 'Celery', category: 'vegetable', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'potato_russet', name: 'Russet Potato', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'potato_yukon', name: 'Yukon Gold Potato', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'sweet_potato', name: 'Sweet Potato', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'broccoli', name: 'Broccoli', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'cauliflower', name: 'Cauliflower', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'spinach', name: 'Spinach', category: 'vegetable', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'kale', name: 'Kale', category: 'vegetable', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'romaine', name: 'Romaine Lettuce', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'iceberg', name: 'Iceberg Lettuce', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'arugula', name: 'Arugula', category: 'vegetable', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'tomato', name: 'Tomato', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'cherry_tomato', name: 'Cherry Tomatoes', category: 'vegetable', default_unit: 'pint', aisle_group: 'produce', shopping_group: null },
  { id: 'bell_pepper_red', name: 'Red Bell Pepper', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'bell_pepper_green', name: 'Green Bell Pepper', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'jalapeno', name: 'Jalapeño', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'cucumber', name: 'Cucumber', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'zucchini', name: 'Zucchini', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'yellow_squash', name: 'Yellow Squash', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'mushroom_white', name: 'White Mushrooms', category: 'vegetable', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'mushroom_baby_bella', name: 'Baby Bella Mushrooms', category: 'vegetable', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'green_bean', name: 'Green Beans', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'asparagus', name: 'Asparagus', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'brussels_sprout', name: 'Brussels Sprouts', category: 'vegetable', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'cabbage_green', name: 'Green Cabbage', category: 'vegetable', default_unit: 'head', aisle_group: 'produce', shopping_group: null },
  { id: 'corn_ear', name: 'Corn on the Cob', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'scallion', name: 'Scallions', category: 'vegetable', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'shallot', name: 'Shallot', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'leek', name: 'Leek', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'avocado', name: 'Avocado', category: 'vegetable', default_unit: 'each', aisle_group: 'produce', shopping_group: null },

  // Produce - fruit
  { id: 'lemon', name: 'Lemon', category: 'fruit', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'lime', name: 'Lime', category: 'fruit', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'orange', name: 'Orange', category: 'fruit', default_unit: 'each', aisle_group: 'produce', shopping_group: null },
  { id: 'apple', name: 'Apple', category: 'fruit', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'banana', name: 'Banana', category: 'fruit', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'strawberry', name: 'Strawberries', category: 'fruit', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'blueberry', name: 'Blueberries', category: 'fruit', default_unit: 'pint', aisle_group: 'produce', shopping_group: null },
  { id: 'raspberry', name: 'Raspberries', category: 'fruit', default_unit: 'pint', aisle_group: 'produce', shopping_group: null },
  { id: 'grape', name: 'Grapes', category: 'fruit', default_unit: 'lb', aisle_group: 'produce', shopping_group: null },
  { id: 'pineapple', name: 'Pineapple', category: 'fruit', default_unit: 'each', aisle_group: 'produce', shopping_group: null },

  // Herbs (fresh)
  { id: 'basil_fresh', name: 'Fresh Basil', category: 'herb', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'cilantro_fresh', name: 'Fresh Cilantro', category: 'herb', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'parsley_fresh', name: 'Fresh Parsley', category: 'herb', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'rosemary_fresh', name: 'Fresh Rosemary', category: 'herb', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'thyme_fresh', name: 'Fresh Thyme', category: 'herb', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'dill_fresh', name: 'Fresh Dill', category: 'herb', default_unit: 'bunch', aisle_group: 'produce', shopping_group: null },
  { id: 'mint_fresh', name: 'Fresh Mint', category: 'herb', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },

  // Meat & poultry
  { id: 'chicken_breast', name: 'Chicken Breast (Boneless, Skinless)', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'chicken_thigh', name: 'Chicken Thighs (Boneless, Skinless)', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'chicken_thigh_bone_in', name: 'Chicken Thighs (Bone-in)', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'chicken_drumstick', name: 'Chicken Drumsticks', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'chicken_whole', name: 'Whole Chicken', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'chicken_wing', name: 'Chicken Wings', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'ground_beef_80', name: 'Ground Beef (80/20)', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'ground_beef_90', name: 'Ground Beef (90/10)', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'beef_chuck', name: 'Beef Chuck Roast', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'beef_sirloin', name: 'Beef Sirloin Steak', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'beef_ribeye', name: 'Ribeye Steak', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'beef_flank', name: 'Flank Steak', category: 'beef', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'pork_chop', name: 'Pork Chops', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'pork_tenderloin', name: 'Pork Tenderloin', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'pork_shoulder', name: 'Pork Shoulder', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'ground_pork', name: 'Ground Pork', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'bacon', name: 'Bacon', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'italian_sausage', name: 'Italian Sausage', category: 'pork', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'ground_turkey', name: 'Ground Turkey', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'turkey_breast', name: 'Turkey Breast', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },
  { id: 'turkey_sausage', name: 'Turkey Sausage', category: 'poultry', default_unit: 'lb', aisle_group: 'meat', shopping_group: null },

  // Seafood
  { id: 'salmon_fillet', name: 'Salmon Fillet', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'tuna_steak', name: 'Tuna Steak', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'shrimp', name: 'Shrimp', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'cod_fillet', name: 'Cod Fillet', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'tilapia_fillet', name: 'Tilapia Fillet', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'mahi_mahi', name: 'Mahi Mahi', category: 'seafood', default_unit: 'lb', aisle_group: 'seafood', shopping_group: null },
  { id: 'tuna_canned', name: 'Canned Tuna', category: 'seafood', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'sardines_canned', name: 'Canned Sardines', category: 'seafood', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },

  // Dairy & eggs
  { id: 'egg_large', name: 'Large Eggs', category: 'dairy', default_unit: 'dozen', aisle_group: 'dairy', shopping_group: null },
  { id: 'milk_whole', name: 'Whole Milk', category: 'dairy', default_unit: 'gal', aisle_group: 'dairy', shopping_group: null },
  { id: 'milk_2', name: '2% Milk', category: 'dairy', default_unit: 'gal', aisle_group: 'dairy', shopping_group: null },
  { id: 'milk_skim', name: 'Skim Milk', category: 'dairy', default_unit: 'gal', aisle_group: 'dairy', shopping_group: null },
  { id: 'butter_unsalted', name: 'Unsalted Butter', category: 'dairy', default_unit: 'lb', aisle_group: 'dairy', shopping_group: null },
  { id: 'butter_salted', name: 'Salted Butter', category: 'dairy', default_unit: 'lb', aisle_group: 'dairy', shopping_group: null },
  { id: 'margarine', name: 'Margarine', category: 'dairy', default_unit: 'lb', aisle_group: 'dairy', shopping_group: null },
  { id: 'heavy_cream', name: 'Heavy Cream', category: 'dairy', default_unit: 'pint', aisle_group: 'dairy', shopping_group: null },
  { id: 'sour_cream', name: 'Sour Cream', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'greek_yogurt_plain', name: 'Plain Greek Yogurt', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cream_cheese', name: 'Cream Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_cheddar', name: 'Cheddar Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_mozzarella', name: 'Mozzarella Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_parmesan', name: 'Parmesan Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_feta', name: 'Feta Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_goat', name: 'Goat Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'cheese_ricotta', name: 'Ricotta Cheese', category: 'dairy', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },

  // Pantry - grains & starches
  { id: 'rice_white_long', name: 'Long-Grain White Rice', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'rice_brown', name: 'Brown Rice', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'rice_basmati', name: 'Basmati Rice', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'rice_jasmine', name: 'Jasmine Rice', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'quinoa', name: 'Quinoa', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'pasta_spaghetti', name: 'Spaghetti', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'pasta_penne', name: 'Penne', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'pasta_rigatoni', name: 'Rigatoni', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'pasta_farfalle', name: 'Farfalle', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'pasta_orzo', name: 'Orzo', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'pasta_linguine', name: 'Linguine', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: 'pasta' },
  { id: 'lasagna_noodle', name: 'Lasagna Noodles', category: 'pasta', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'noodle_ramen', name: 'Ramen Noodles', category: 'pasta', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'noodle_udon', name: 'Udon Noodles', category: 'pasta', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'noodle_rice', name: 'Rice Noodles', category: 'pasta', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'flour_ap', name: 'All-Purpose Flour', category: 'baking', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'flour_bread', name: 'Bread Flour', category: 'baking', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'oats_rolled', name: 'Rolled Oats', category: 'grain', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'bread_sliced', name: 'Sliced Bread', category: 'bread', default_unit: 'loaf', aisle_group: 'bakery', shopping_group: null },
  { id: 'bread_baguette', name: 'Baguette', category: 'bread', default_unit: 'each', aisle_group: 'bakery', shopping_group: null },
  { id: 'tortilla_flour', name: 'Flour Tortillas', category: 'bread', default_unit: 'pack', aisle_group: 'bakery', shopping_group: null },
  { id: 'tortilla_corn', name: 'Corn Tortillas', category: 'bread', default_unit: 'pack', aisle_group: 'bakery', shopping_group: null },
  { id: 'bun_hamburger', name: 'Hamburger Buns', category: 'bread', default_unit: 'pack', aisle_group: 'bakery', shopping_group: null },
  { id: 'bun_hotdog', name: 'Hot Dog Buns', category: 'bread', default_unit: 'pack', aisle_group: 'bakery', shopping_group: null },
  { id: 'panko', name: 'Panko Breadcrumbs', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Pantry - beans & legumes
  { id: 'black_bean_canned', name: 'Canned Black Beans', category: 'legume', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'kidney_bean_canned', name: 'Canned Kidney Beans', category: 'legume', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'chickpea_canned', name: 'Canned Chickpeas', category: 'legume', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'pinto_bean_canned', name: 'Canned Pinto Beans', category: 'legume', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'cannellini_canned', name: 'Canned Cannellini Beans', category: 'legume', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'lentil_dry', name: 'Dry Lentils', category: 'legume', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },

  // Pantry - canned & jarred
  { id: 'tomato_crushed_canned', name: 'Canned Crushed Tomatoes', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'tomato_diced_canned', name: 'Canned Diced Tomatoes', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'tomato_paste', name: 'Tomato Paste', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'tomato_sauce_canned', name: 'Canned Tomato Sauce', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'pasta_sauce_jar', name: 'Jarred Pasta Sauce', category: 'canned', default_unit: 'jar', aisle_group: 'pantry', shopping_group: null },
  { id: 'salsa_jar', name: 'Salsa', category: 'canned', default_unit: 'jar', aisle_group: 'pantry', shopping_group: null },
  { id: 'coconut_milk_canned', name: 'Canned Coconut Milk', category: 'canned', default_unit: 'can', aisle_group: 'pantry', shopping_group: null },
  { id: 'broth_chicken', name: 'Chicken Broth', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'broth_vegetable', name: 'Vegetable Broth', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'broth_beef', name: 'Beef Broth', category: 'canned', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Pantry - oils, vinegars, condiments
  { id: 'olive_oil', name: 'Olive Oil', category: 'oil', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vegetable_oil', name: 'Vegetable Oil', category: 'oil', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'sesame_oil', name: 'Sesame Oil', category: 'oil', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vinegar_white', name: 'White Vinegar', category: 'vinegar', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vinegar_apple_cider', name: 'Apple Cider Vinegar', category: 'vinegar', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vinegar_balsamic', name: 'Balsamic Vinegar', category: 'vinegar', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vinegar_rice', name: 'Rice Vinegar', category: 'vinegar', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'soy_sauce', name: 'Soy Sauce', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'fish_sauce', name: 'Fish Sauce', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'hot_sauce', name: 'Hot Sauce', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'sriracha', name: 'Sriracha', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'ketchup', name: 'Ketchup', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'mustard_dijon', name: 'Dijon Mustard', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'mustard_yellow', name: 'Yellow Mustard', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'mayo', name: 'Mayonnaise', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'honey', name: 'Honey', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'maple_syrup', name: 'Maple Syrup', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'peanut_butter', name: 'Peanut Butter', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'jam_strawberry', name: 'Strawberry Jam', category: 'condiment', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Spices & seasonings
  { id: 'salt_kosher', name: 'Kosher Salt', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'pepper_black', name: 'Black Pepper', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'garlic_powder', name: 'Garlic Powder', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'onion_powder', name: 'Onion Powder', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'paprika', name: 'Paprika', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'smoked_paprika', name: 'Smoked Paprika', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cumin_ground', name: 'Ground Cumin', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'coriander_ground', name: 'Ground Coriander', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'chili_powder', name: 'Chili Powder', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cayenne', name: 'Cayenne', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'red_pepper_flakes', name: 'Red Pepper Flakes', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cinnamon_ground', name: 'Ground Cinnamon', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'oregano_dried', name: 'Dried Oregano', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'basil_dried', name: 'Dried Basil', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'thyme_dried', name: 'Dried Thyme', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'bay_leaf', name: 'Bay Leaves', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'italian_seasoning', name: 'Italian Seasoning', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'curry_powder', name: 'Curry Powder', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'garam_masala', name: 'Garam Masala', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'turmeric', name: 'Turmeric', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'ginger_ground', name: 'Ground Ginger', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'nutmeg', name: 'Nutmeg', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'vanilla_extract', name: 'Vanilla Extract', category: 'spice', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Sweeteners & baking
  { id: 'sugar_white', name: 'White Sugar', category: 'baking', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'sugar_brown', name: 'Brown Sugar', category: 'baking', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'sugar_powdered', name: 'Powdered Sugar', category: 'baking', default_unit: 'lb', aisle_group: 'pantry', shopping_group: null },
  { id: 'baking_powder', name: 'Baking Powder', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'baking_soda', name: 'Baking Soda', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'yeast', name: 'Active Dry Yeast', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cornstarch', name: 'Cornstarch', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cocoa_powder', name: 'Cocoa Powder', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'chocolate_chip', name: 'Chocolate Chips', category: 'baking', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Nuts & seeds
  { id: 'almond', name: 'Almonds', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'walnut', name: 'Walnuts', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'pecan', name: 'Pecans', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'cashew', name: 'Cashews', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'peanut', name: 'Peanuts', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'pine_nut', name: 'Pine Nuts', category: 'nut', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'sesame_seed', name: 'Sesame Seeds', category: 'seed', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'chia_seed', name: 'Chia Seeds', category: 'seed', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },
  { id: 'flax_seed', name: 'Flax Seeds', category: 'seed', default_unit: 'oz', aisle_group: 'pantry', shopping_group: null },

  // Frozen
  { id: 'frozen_peas', name: 'Frozen Peas', category: 'frozen', default_unit: 'oz', aisle_group: 'frozen', shopping_group: null },
  { id: 'frozen_corn', name: 'Frozen Corn', category: 'frozen', default_unit: 'oz', aisle_group: 'frozen', shopping_group: null },
  { id: 'frozen_broccoli', name: 'Frozen Broccoli', category: 'frozen', default_unit: 'oz', aisle_group: 'frozen', shopping_group: null },
  { id: 'frozen_spinach', name: 'Frozen Spinach', category: 'frozen', default_unit: 'oz', aisle_group: 'frozen', shopping_group: null },
  { id: 'frozen_berry_mix', name: 'Frozen Berry Mix', category: 'frozen', default_unit: 'oz', aisle_group: 'frozen', shopping_group: null },
  { id: 'ice_cream_vanilla', name: 'Vanilla Ice Cream', category: 'frozen', default_unit: 'pint', aisle_group: 'frozen', shopping_group: null },
  { id: 'frozen_pizza', name: 'Frozen Pizza', category: 'frozen', default_unit: 'each', aisle_group: 'frozen', shopping_group: null },

  // Deli / misc
  { id: 'deli_turkey', name: 'Deli Turkey', category: 'deli', default_unit: 'lb', aisle_group: 'deli', shopping_group: null },
  { id: 'deli_ham', name: 'Deli Ham', category: 'deli', default_unit: 'lb', aisle_group: 'deli', shopping_group: null },
  { id: 'hummus', name: 'Hummus', category: 'deli', default_unit: 'oz', aisle_group: 'deli', shopping_group: null },
  { id: 'olives', name: 'Olives', category: 'deli', default_unit: 'oz', aisle_group: 'deli', shopping_group: null },
  { id: 'pickles', name: 'Pickles', category: 'condiment', default_unit: 'jar', aisle_group: 'pantry', shopping_group: null },
  { id: 'tofu_firm', name: 'Firm Tofu', category: 'protein', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'tofu_extra_firm', name: 'Extra Firm Tofu', category: 'protein', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },
  { id: 'tempeh', name: 'Tempeh', category: 'protein', default_unit: 'oz', aisle_group: 'produce', shopping_group: null },

  // Beverages
  { id: 'coffee_ground', name: 'Ground Coffee', category: 'beverage', default_unit: 'oz', aisle_group: 'beverage', shopping_group: null },
  { id: 'tea_black', name: 'Black Tea', category: 'beverage', default_unit: 'oz', aisle_group: 'beverage', shopping_group: null },
  { id: 'oj', name: 'Orange Juice', category: 'beverage', default_unit: 'oz', aisle_group: 'dairy', shopping_group: null },
  { id: 'sparkling_water', name: 'Sparkling Water', category: 'beverage', default_unit: 'liter', aisle_group: 'beverage', shopping_group: null },

  // Snacks
  { id: 'tortilla_chips', name: 'Tortilla Chips', category: 'snack', default_unit: 'oz', aisle_group: 'snack', shopping_group: null },
  { id: 'crackers', name: 'Crackers', category: 'snack', default_unit: 'oz', aisle_group: 'snack', shopping_group: null },
  { id: 'granola_bar', name: 'Granola Bars', category: 'snack', default_unit: 'box', aisle_group: 'snack', shopping_group: null },
];
